version: '3.4'

services:
  awardwiz:
    image: awardwiz
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
